config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :public_guests, except: [:show]
    resources :schedule_events, except: [:show]
    resources :rounds, only: [:index, :edit, :update] do
      patch 'assign_stations' => 'rounds#assign_stations'
    end

    get '/schedule' => 'rounds#schedule'

    get '/wcif' => 'registrations#show_wcif'

    #FIXME: removed in favor of doing this in the WCA website
    #patch 'rounds/add/:event_id' => 'rounds#add', :as => :add_round
    #patch 'rounds/remove/:event_id' => 'rounds#remove', :as => :remove_round

    get 'registrations/random' => 'registrations#random'

    resources :registrations, only: [:index, :edit, :update] do
      get 'groups' => 'groups#show_for_registration'
      get 'schedule' => 'registrations#schedule'
    end

    get 'registrations/staff' => 'registrations#staff'
    get 'registrations/psy/:event_id' => 'registrations#psych_sheet'

    get 'mails' => 'registrations#mails'
    get 'names' => 'registrations#names'
    get 'badges' => 'registrations#badges'
    get 'top3' => 'registrations#top3'
    get 'registrations/cleanup' => 'registrations#cleanup'

    get 'printing' => 'printing#index'
    get 'printable_schedules' => 'printing#printable_schedules'
    get 'printable_groups' => 'printing#printable_groups'
    get 'printable_groups_only' => 'printing#printable_groups_only'
    get 'printable_groups_schedule' => 'printing#printable_groups_schedule'
    get 'printable_rounds_schedule' => 'printing#printable_rounds_schedule'
    get 'printable_teams' => 'printing#printable_teams'
    get 'rooms_side' => 'printing#rooms_side'

    resources :groups, param: :group_id
    resources :groups, only: [] do
      patch 'staff' => 'groups#update_staff'
    end

    resources :staff_teams do
      get 'schedule' => 'staff_teams#schedule'
    end

    get 'groups-schedule' => 'groups#schedule', :as => :groups_schedule
    get 'groups/e/:event_id' => 'groups#show_for_event', :as => :groups_for_event
    get 'groups/r/:round_id' => 'groups#show_for_round', :as => :groups_for_round
    get 'groups/for_round/:round_id' => 'groups#groups_repartition_for_round', :as => :groups_repartition_for_round
    patch 'groups/move_to/:round_id/(:group_id/:registration_ids)' => 'groups#move_registrations_to_group', :as => :move_to_group
    patch 'groups/drop_group_from/:round_id(/:registration_ids)' => 'groups#drop_groups_from_round', :as => :drop_group_for_round
    patch 'groups/clear_for/:round_id' => 'groups#clear_groups_for_round', :as => :clear_groups_for_round
    patch 'groups/r/:round_id' => 'groups#update_for_round'
    patch 'groups/create_for_round/:round_id' => 'groups#create_groups_for_round', :as => :create_groups_for_round
    patch 'groups/add_everyone_to_all/:round_id' => 'groups#add_everyone_to_all_groups', :as => :fm_mbf_special_fill

    delete 'registration_groups/:id' => 'groups#destroy_registration_group', :as => :delete_from_group

    patch 'groups/autogenerate/:round_id' => 'groups#autogenerate_group', :as => :generate_groups
    get 'groups/generate/:group_id/:direction(/:n)' => 'groups#top_low_to_group', :as => :top_low_groups
    get 'groups/fill/:round_id(/:n)' => 'groups#fill_remaining_groups', :as => :fill_remaining

    post '/confirm' => 'registrations#confirm'
    get '/my_registration' => 'registrations#edit'
    get '/my_schedule' => 'registrations#schedule'

    get '/competition' => 'competitions#show'
    patch '/competition' => 'competitions#update'
    get '/competition/setup' => 'competitions#setup'
    patch '/competition/import/:competition_id' => 'competitions#import_competition', :as => :competition_import
    post '/competition/reset' => 'competitions#reset'
    patch '/competition/import_wcif' => 'competitions#import_wcif', :as => :import_wcif
    patch '/competition/export_wcif' => 'competitions#export_wcif', :as => :export_wcif

    root to: 'visitors#index'

    get '/wca_callback' => 'sessions#create'
    get '/signin' => 'sessions#new', :as => :signin
    post '/signin' => 'sessions#signin_with_wca', :as => :signin_with_wca
    get '/wca_down' => 'sessions#anon_staff'
    post '/wca_down' => 'sessions#login_anon_staff'
    get '/signout' => 'sessions#destroy', :as => :signout
  end
end

app/models/public_guest.rb
class PublicGuest < ApplicationRecord
  # email spec is too hard to validate precisely, use an approximate format
  validates_format_of :email, with: /\A[^@,\s]+@[^@,\s]+\.[^@,\s]+\z/
end

app/controllers/public_guests_controller.rb
class PublicGuestsController < ApplicationController
  before_action :set_public_guest, only: [:edit, :update, :destroy]
  before_action :redirect_unless_admin!, except: [:index, :new, :create]

  # GET /public_guests
  # GET /public_guests.json
  def index
    @public_guests = PublicGuest.all
    # tmp fix for Euro
    render :noop
  end

  # GET /public_guests/new
  def new
    @public_guest = PublicGuest.new
  end

  # GET /public_guests/1/edit
  def edit
  end

  # POST /public_guests
  # POST /public_guests.json
  def create
    @public_guest = PublicGuest.new(public_guest_params)

    if @public_guest.save
      flash[:success] = 'Public guest was successfully created.'
      redirect_to public_guests_url
    else
      render :new
    end
  end

  # PATCH/PUT /public_guests/1
  # PATCH/PUT /public_guests/1.json
  def update
    if @public_guest.update(public_guest_params)
      flash[:success] = 'Public guest was successfully updated.'
      redirect_to public_guests_url
    else
      render :edit
    end
  end

  # DELETE /public_guests/1
  # DELETE /public_guests/1.json
  def destroy
    @public_guest.destroy
    flash[:success] = 'Public guest was successfully destroyed.'
    redirect_to public_guests_url
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_public_guest
      @public_guest = PublicGuest.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def public_guest_params
      params.require(:public_guest).permit(:fullname, :email)
    end
end

app/helpers/public_guests_helper.rb
module PublicGuestsHelper
end

app/views/public_guests/_form.html.erb
<%= simple_form_for(@public_guest) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :fullname %>
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <% submit_value = @public_guest.new_record? ? t('public_guests.form.submit_new') : t('public_guests.form.submit_update') %>
    <%# FIXME: onclick the button's text changes... %>
    <%= f.button :submit, value: submit_value %>
  </div>
<% end %>

app/views/public_guests/edit.html.erb
<h1>Editing Public Guest</h1>

<%= render 'form', public_guest: @public_guest %>

<%= link_to 'Back', public_guests_path %>

app/views/public_guests/index.html.erb
<p id="notice"><%= notice %></p>

<h2><%= t('public_guests.competitors.title' ) %></h2>
<b><%= t('public_guests.do_not_register_here') %></b>
<%= t('public_guests.competitors.explanations_html',wca_website: link_to(t('public_guests.competitors.wca_website'), "https://www.worldcubeassociation.org/competitions/France2018/register"),my_registration_link: link_to(t('public_guests.competitors.here'), my_registration_url)) %>

<h2><%= t('public_guests.visitors_guests.title') %></h2>
<b><%= t('public_guests.do_not_register_here') %></b>
<%= t('public_guests.visitors_guests.explanation_html',rd_page: link_to(t('public_guests.visitors_guests.registration_details_page'), my_registration_url)) %>

<h2><%= t('public_guests.other_visitors.title') %></h2>
<%= t('public_guests.other_visitors.explanations') %>
<br/>
<%= t('public_guests.other_visitors.conditions') %>
<br/>
<br/>
<p>
  <%= link_to t('public_guests.other_visitors.register_here'), new_public_guest_path, class: "btn btn-primary" %>
</p>

<h2><%= t('public_guests.list.title') %></h2>

<table class="table table-hover"
  <% if current_user&.can_manage_competition? %>
    data-toggle="table"
    data-search="true"
  <% end %>
       id="table-visitors">
  <thead>
    <tr>
      <th><%= t('public_guests.list.fullname') %></th>
      <% if current_user&.can_manage_competition? %>
        <th><%= t('public_guests.list.email') %></th>
        <th><%= t('public_guests.list.actions') %></th>
      <% end %>
    </tr>
  </thead>

  <tbody>
    <% @public_guests.each do |public_guest| %>
      <tr>
        <td><%= public_guest.fullname %></td>
        <% if current_user&.can_manage_competition? %>
          <td><%= public_guest.email %></td>
          <td>
            <%= link_to t('usual_buttons.edit'), edit_public_guest_path(public_guest) %>
            <%= link_to t('usual_buttons.destroy'), public_guest, method: :delete, data: { confirm: t('alerts.are_you_sure') } %>
          </td>
        <% end %>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/public_guests/new.html.erb
<h1><%= t('public_guests.new.title') %></h1>

<%= render 'form', public_guest: @public_guest %>

<%= link_to t('public_guests.new.link_back'), public_guests_path %>