config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :public_guests, except: [:show]
    resources :schedule_events, except: [:show]
    resources :rounds, only: [:index, :edit, :update] do
      patch 'assign_stations' => 'rounds#assign_stations'
    end

    get '/schedule' => 'rounds#schedule'

    get '/wcif' => 'registrations#show_wcif'

    #FIXME: removed in favor of doing this in the WCA website
    #patch 'rounds/add/:event_id' => 'rounds#add', :as => :add_round
    #patch 'rounds/remove/:event_id' => 'rounds#remove', :as => :remove_round

    get 'registrations/random' => 'registrations#random'

    resources :registrations, only: [:index, :edit, :update] do
      get 'groups' => 'groups#show_for_registration'
      get 'schedule' => 'registrations#schedule'
    end

    get 'registrations/staff' => 'registrations#staff'
    get 'registrations/psy/:event_id' => 'registrations#psych_sheet'

    get 'mails' => 'registrations#mails'
    get 'names' => 'registrations#names'
    get 'badges' => 'registrations#badges'
    get 'top3' => 'registrations#top3'
    get 'registrations/cleanup' => 'registrations#cleanup'

    get 'printing' => 'printing#index'
    get 'printable_schedules' => 'printing#printable_schedules'
    get 'printable_groups' => 'printing#printable_groups'
    get 'printable_groups_only' => 'printing#printable_groups_only'
    get 'printable_groups_schedule' => 'printing#printable_groups_schedule'
    get 'printable_rounds_schedule' => 'printing#printable_rounds_schedule'
    get 'printable_teams' => 'printing#printable_teams'
    get 'rooms_side' => 'printing#rooms_side'

    resources :groups, param: :group_id
    resources :groups, only: [] do
      patch 'staff' => 'groups#update_staff'
    end

    resources :staff_teams do
      get 'schedule' => 'staff_teams#schedule'
    end

    get 'groups-schedule' => 'groups#schedule', :as => :groups_schedule
    get 'groups/e/:event_id' => 'groups#show_for_event', :as => :groups_for_event
    get 'groups/r/:round_id' => 'groups#show_for_round', :as => :groups_for_round
    get 'groups/for_round/:round_id' => 'groups#groups_repartition_for_round', :as => :groups_repartition_for_round
    patch 'groups/move_to/:round_id/(:group_id/:registration_ids)' => 'groups#move_registrations_to_group', :as => :move_to_group
    patch 'groups/drop_group_from/:round_id(/:registration_ids)' => 'groups#drop_groups_from_round', :as => :drop_group_for_round
    patch 'groups/clear_for/:round_id' => 'groups#clear_groups_for_round', :as => :clear_groups_for_round
    patch 'groups/r/:round_id' => 'groups#update_for_round'
    patch 'groups/create_for_round/:round_id' => 'groups#create_groups_for_round', :as => :create_groups_for_round
    patch 'groups/add_everyone_to_all/:round_id' => 'groups#add_everyone_to_all_groups', :as => :fm_mbf_special_fill

    delete 'registration_groups/:id' => 'groups#destroy_registration_group', :as => :delete_from_group

    patch 'groups/autogenerate/:round_id' => 'groups#autogenerate_group', :as => :generate_groups
    get 'groups/generate/:group_id/:direction(/:n)' => 'groups#top_low_to_group', :as => :top_low_groups
    get 'groups/fill/:round_id(/:n)' => 'groups#fill_remaining_groups', :as => :fill_remaining

    post '/confirm' => 'registrations#confirm'
    get '/my_registration' => 'registrations#edit'
    get '/my_schedule' => 'registrations#schedule'

    get '/competition' => 'competitions#show'
    patch '/competition' => 'competitions#update'
    get '/competition/setup' => 'competitions#setup'
    patch '/competition/import/:competition_id' => 'competitions#import_competition', :as => :competition_import
    post '/competition/reset' => 'competitions#reset'
    patch '/competition/import_wcif' => 'competitions#import_wcif', :as => :import_wcif
    patch '/competition/export_wcif' => 'competitions#export_wcif', :as => :export_wcif

    root to: 'visitors#index'

    get '/wca_callback' => 'sessions#create'
    get '/signin' => 'sessions#new', :as => :signin
    post '/signin' => 'sessions#signin_with_wca', :as => :signin_with_wca
    get '/wca_down' => 'sessions#anon_staff'
    post '/wca_down' => 'sessions#login_anon_staff'
    get '/signout' => 'sessions#destroy', :as => :signout
  end
end

app/models/competition.rb
class Competition < ApplicationRecord
  include WCAModel
  # Group visibility permissions, from the strongest (admin) to the weakest (all)
  GROUPS_VISIBILITIES = %w(admin staff all).freeze
  # List of models to clear up.
  # 'User' is intentionally left there.
  # FIXME: there must be a better way...
  MODEL_USED = [
    Competition, Group, Guest, PersonRoundColor, PersonalBest,
    PublicGuest, RegistrationDetail, RegistrationGroup, Registration,
    Round, ScheduleEvent, ScrambleEvent, StaffRegistrationsGroup,
    StaffTeam, StaffTeamMember, StaffTeamsGroup, CompetitionVenue, VenueRoom
  ].freeze

  WCIF_ASSOCIATIONS = {
    registrations: {
      groups: [:round],
      staff_registrations_groups: {
        group: [:round],
      },
      staff_teams_groups: {
        group: [:round],
      },
      scramble_events: [],
      competition: [],
      personal_bests: [],
      user: [],
      registration_detail: [],
    },
    competition_venues: {
      venue_rooms: {
        rounds: [:groups],
        schedule_events: [],
      },
    },
  }.freeze


  has_many :registrations
  has_many :competition_venues, dependent: :destroy


  validates :name, presence: true
  validates :admin_ids, presence: true, allow_blank: false
  validates_inclusion_of :groups_visibility, in: GROUPS_VISIBILITIES

  attr_accessor :last_id

  # NOTE: we *should* be validating start_date <= end_date,
  # but we fetch data from the WCA and we assume it's alright.

  @@obj_info = %w(id name admin_ids start_date end_date)

  def admins_array
    @admins_array ||= admin_ids.split(",").map(&:to_i)
  end

  def number_of_days
    (end_date - start_date).to_i + 1
  end

  def start_time
    # Take the easternmost offset
    start_date.to_time.change(offset: "+14:00")
  end

  def end_time
    # Take the westernmost offset
    (end_date + 1).to_time.change(offset: "-12:00")
  end

  def groups_visible_for_all?
    groups_visibility == "all"
  end

  def groups_visible_for_staff?
    groups_visibility == "staff"
  end

  def to_wcif
    {
      "formatVersion" => "1.0",
      "id" => id,
      "name" => name,
      "shortName" => name,
      "persons" => registrations.sort_by { |r| r.registrant_id }.map(&:to_wcif),
      "schedule" => {
        "startDate": start_date,
        "numberOfDays": number_of_days,
        "venues": competition_venues.map(&:to_wcif),
      },
      "extensions": [{
        id: "groupifier.CompetitionConfig",
        specUrl: "https://groupifier.jonatanklosko.com/wcif-extensions/CompetitionConfig.json",
        data: {
          localNamesFirst: false,
          scorecardsBackgroundUrl: "",
          competitorsSortingRule: "ranks",
          noTasksForNewcomers: true,
          tasksForOwnEventsOnly: true,
          noRunningForForeigners: false,
          printStations: true,
          scorecardPaperSize: "a4",
        },
      }],
    }
  end

  def self.convert_to_zone_and_strip(datetime_string, tz_string)
    # Fullcalendar will use ambiguously zoned time (ie: will strip the timezone),
    # so we need to store all the datetime in the same timezone
    # (chosen arbitrarily to be UTC).
    # Any external datetime is properly formatted with a timezone (we're the bad guys here),
    # so we need to first convert the datetime to its timezone,
    # then "replace" the zone with UTC without changing the time

    # This turns:
    # Sat, 08 Sep 2018 07:55:00 UTC +00:00
    # into
    # Sat, 08 Sep 2018 09:55:00 CEST +02:00
    itz = DateTime.parse(datetime_string).in_time_zone(tz_string)
    # This turns itz into
    # 2018-09-08 09:55:00 UTC
    ActiveSupport::TimeZone.new("UTC").local_to_utc(itz)
  end

  def self.next_activity_wcif_id
    # ScheduleEvent/Round/Group should be the only sources of activities
    (ScheduleEvent.pluck(:wcif_id) + Round.pluck(:wcif_id) + Group.pluck(:wcif_id)).max + 1
  end

  def import_results(wcif)
    events = wcif["events"]
    return unless events

    events.each do |e|
      e["rounds"].each do |r|
        parts = Group.parse_activity_code(r["id"])
        round = Round.find_by(event_id: parts[:event_id], r_id: parts[:round_number])
        next unless round
        registrant_ids = r["results"].map { |person| person["personId"] }.join(",")
        round.update(registrant_ids: registrant_ids)
      end
    end
  end

  def import_schedule(wcif)
    # TODO: validate the schema!
    schedule = wcif["schedule"]
    return unless schedule

    venues = schedule["venues"]
    return unless venues

    activities = []
    timezone = "UTC"
    new_venues = venues.map do |venue_wcif|
      venue = competition_venues.find { |v| v.wcif_id == venue_wcif["id"] } || competition_venues.build
      venue.load_wcif!(venue_wcif)
    end
    # This also cleans up old venues
    self.competition_venues = new_venues
  end
end

app/controllers/competitions_controller.rb
class CompetitionsController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_if_already_setup!, only: [:setup]
  before_action :redirect_unless_admin!, only: [:show, :update]

  skip_before_action :redirect_unless_setup!, only: [:setup, :import_competition]

  def show
  end

  def update
    if managed_competition.update(settings_params)
      redirect_to competition_path, flash: { success: 'Settings updated' }
    else
      render :show
    end
  end


  def setup
    @my_competitions = []
    @error = nil
    begin
      comps_response = RestClient.get(wca_api_competitions_url, { Authorization: "Bearer #{session[:access_token]}", params: { managed_by_me: true, start: 2.days.ago.to_date} })
      @my_competitions = JSON.parse(comps_response.body)
    rescue RestClient::ExceptionWithResponse => err
      @error = err
    end
  end

  def import_competition
    competition_id = params.require(:competition_id)
    begin
      competition_response = RestClient.get(wca_api_competitions_url(competition_id), { Authorization: "Bearer #{session[:access_token]}" })
      competition_data = JSON.parse(competition_response.body)
      admins = competition_data["organizers"] + competition_data["delegates"]
      obj_attr = {
        admin_ids: admins.map { |person| person["id"] }.uniq.join(",")
      }
      status, competition = Competition.wca_create_or_update(competition_data, obj_attr)
      unless status
        throw RestClient::ExceptionWithResponse.new
      end
      redirect_to competition_url
    rescue RestClient::ExceptionWithResponse => err
      redirect_to(competition_setup_url, alert: "Failed to fetch competition info")
    end
  end

  def import_wcif
    source = params.require(:source)
    wcif_string_content = ""
    case source
    when "wca"
      begin
        registrations_response = RestClient.get(wca_api_url("/competitions/#{managed_competition.id}/wcif"), { Authorization: "Bearer #{session[:access_token]}"})
        wcif_string_content = registrations_response.body
      rescue RestClient::ExceptionWithResponse => err
        return redirect_to(registrations_url, alert: "Failed to fetch WCA data: #{err.message}")
      end
    when "url"
      # We're loading remote content. It's extremely dangerous, but hopefully only rightful people have access to this
      remote_url = params.require(:wcif).require(:url)
      begin
        wcif_response = RestClient.get(remote_url)
        wcif_string_content = wcif_response.body
      rescue RestClient::ExceptionWithResponse => err
        return redirect_to(registrations_url, alert: "Failed to fetch url data: #{err.message}")
      end
    else
      raise ArgumentError.new("Only 'wca' and 'file' are supported.")
    end
    wcif = JSON.parse(wcif_string_content)

    unless managed_competition.id == wcif["id"]
      return redirect_to(competition_url, flash: { danger: "WCIF is for the wrong competition!" })
    end

    managed_competition.import_schedule(wcif)
    registrations_size = Registration.import_registrations(wcif)
    managed_competition.import_results(wcif)

    redirect_to(schedule_url, flash: { success: "Imported #{registrations_size} registrations and users successfully!" })
  end

  def export_wcif
    comp = Competition.includes(Competition::WCIF_ASSOCIATIONS).find_by_id!(managed_competition.id)
    begin
      update_response = RestClient.patch(
        wca_api_url("/competitions/#{managed_competition.id}/wcif"),
        { "_json": comp.to_wcif }.to_json,
        { Authorization: "Bearer #{session[:access_token]}", content_type: :json }
      )
      redirect_to(competition_path, flash: { success: "Saved to the WCA successfully!" })
    rescue RestClient::ExceptionWithResponse => err
      return redirect_to(competition_url, alert: "Failed to saved to the WCA #{err.message}")
    end
  end

  def reset
    confirmation = params.require(:delete_all).permit(:confirm)
    if confirmation[:confirm] == managed_competition.id
      Competition::MODEL_USED.each do |m|
        m.delete_all
      end
      redirect_to competition_setup_url
    else
      redirect_to competition_url, flash: { danger: "Confirmation doesn't match the competition's id!" }
    end
  end

  private def redirect_if_already_setup!
    if managed_competition
      redirect_to competition_url, flash: { danger: "Application already setup" }
    end
  end

  def settings_params
    params.require(:competition).permit([:groups_visibility])
  end
end

app/views/competitions/setup.html.erb
<% provide(:title, "Setup the competition") %>
<h1 class="text-center">Setup the competition</h1>

<% unless session[:scopes].include?("manage_competitions") %>
  <%= alert :danger do %>
    You didn't authorize this application to manage your competitions when loging in.
    Please <%= link_to "log out", signout_path %> and log in again ticking the appropriate checkbox on the login form.
  <% end %>
<% end %>
<%= alert :danger, "An error occurred when getting your competition: #{@error}" if @error %>
<div class="panel panel-default">
  <div class="panel-heading">
    Your upcoming competitions
  </div>
  <div class="panel-body">
    <% if @my_competitions.empty? %>
      You don't manage any upcoming competitions.
    <% else %>
      <p>Click an upcoming competition to setup this application for it.</p>
      <div class="list-group">
        <% @my_competitions.each do |c| %>
          <%= link_to c["name"], competition_import_path(competition_id: c["id"]), method: "patch", class: "list-group-item" %>
        <% end %>
      </div>
    <% end %>
  </div>
</div>

app/views/competitions/show.html.erb
<div class="container">
  <h1>Application setup for <%= managed_competition.name %></h1>
  <p>You can adjust the settings for the competition below:</p>
  <%= simple_form_for managed_competition, url: competition_path do |f| %>
    <%= f.input :groups_visibility, collection: Competition::GROUPS_VISIBILITIES %>
    <%= f.button :submit, class: "btn-primary", value: "Save competition's settings" %>
  <% end %>
  <hr/>
  <div class="panel panel-primary">
    <div class="panel-heading">
      Import data
    </div>
    <div class="panel-body">
      <p>Data can be (re)-imported from a WCIF.</p>
      <div class="row">
        <div class="col-xs-12 col-md-6 text-center">
          <%= image_tag "wca_logo.svg", width: "140px" %>
          <%= link_to "Import from the WCA", import_wcif_path(source: "wca"), method: "patch", class: "btn btn-primary" %>
        </div>
        <div class="col-xs-12 col-md-6 text-center">
          <%= simple_form_for :wcif, url: import_wcif_path(source: 'url'), method: :patch do |f| %>
            <%= icon("link", style: "font-size: 100px") %><br/>
            <%= f.input :url, label: false %>
            <%= f.submit class: "btn btn-primary", value: "Import from an URL" %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
  <div class="panel panel-primary">
    <div class="panel-heading">
      Export data
    </div>
    <div class="panel-body">
      <p>Data can be saved back, either by downloading the WCIF, or by syncing back to the WCA.</p>
      <div class="row">
        <div class="col-xs-12 col-md-6 text-center">
          <% if managed_competition.competition_venues.any? %>
            <div class="alert alert-danger">
              This will override the competition's schedule and people's assignment
              on the WCA website!
            </div>
            <%= image_tag "wca_logo.svg", width: "140px" %>
            <%= link_to "Save to the WCA", export_wcif_path, method: "patch", class: "btn btn-primary" %>
        <% else %>
          <div class="alert alert-danger">
            It looks like the schedule is empty, I will not let you save to the
            WCA.
          </div>
        <% end %>
        </div>
        <div class="col-xs-12 col-md-6 text-center">
          <%= icon("link", style: "font-size: 100px") %><br/>
          <%= link_to "Download WCIF", wcif_path(format: :json), class: "btn btn-primary" %>
        </div>
      </div>
    </div>
  </div>
  <hr/>
  <div class="panel panel-danger">
    <div class="panel-heading">
      <%= link_to "Danger Zone!", "https://www.youtube.com/watch?v=kUsFWO08CO0", target: "_blank", class: "text-danger" %>
    </div>
    <div class="panel-body">
      <%= simple_form_for :delete_all, url: competition_reset_path do |f| %>
        <%= f.button :submit, class: "delete-btn", value: "Delete everything" %>
        <%= f.input :confirm, as: :string, label: "Confirm with the competition's id:", hint: "There is no turning back", input_html: { autocomplete: "off" } %>
      <% end %>
    </div>
  </div>
</div>