config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :public_guests, except: [:show]
    resources :schedule_events, except: [:show]
    resources :rounds, only: [:index, :edit, :update] do
      patch 'assign_stations' => 'rounds#assign_stations'
    end

    get '/schedule' => 'rounds#schedule'

    get '/wcif' => 'registrations#show_wcif'

    #FIXME: removed in favor of doing this in the WCA website
    #patch 'rounds/add/:event_id' => 'rounds#add', :as => :add_round
    #patch 'rounds/remove/:event_id' => 'rounds#remove', :as => :remove_round

    get 'registrations/random' => 'registrations#random'

    resources :registrations, only: [:index, :edit, :update] do
      get 'groups' => 'groups#show_for_registration'
      get 'schedule' => 'registrations#schedule'
    end

    get 'registrations/staff' => 'registrations#staff'
    get 'registrations/psy/:event_id' => 'registrations#psych_sheet'

    get 'mails' => 'registrations#mails'
    get 'names' => 'registrations#names'
    get 'badges' => 'registrations#badges'
    get 'top3' => 'registrations#top3'
    get 'registrations/cleanup' => 'registrations#cleanup'

    get 'printing' => 'printing#index'
    get 'printable_schedules' => 'printing#printable_schedules'
    get 'printable_groups' => 'printing#printable_groups'
    get 'printable_groups_only' => 'printing#printable_groups_only'
    get 'printable_groups_schedule' => 'printing#printable_groups_schedule'
    get 'printable_rounds_schedule' => 'printing#printable_rounds_schedule'
    get 'printable_teams' => 'printing#printable_teams'
    get 'rooms_side' => 'printing#rooms_side'

    resources :groups, param: :group_id
    resources :groups, only: [] do
      patch 'staff' => 'groups#update_staff'
    end

    resources :staff_teams do
      get 'schedule' => 'staff_teams#schedule'
    end

    get 'groups-schedule' => 'groups#schedule', :as => :groups_schedule
    get 'groups/e/:event_id' => 'groups#show_for_event', :as => :groups_for_event
    get 'groups/r/:round_id' => 'groups#show_for_round', :as => :groups_for_round
    get 'groups/for_round/:round_id' => 'groups#groups_repartition_for_round', :as => :groups_repartition_for_round
    patch 'groups/move_to/:round_id/(:group_id/:registration_ids)' => 'groups#move_registrations_to_group', :as => :move_to_group
    patch 'groups/drop_group_from/:round_id(/:registration_ids)' => 'groups#drop_groups_from_round', :as => :drop_group_for_round
    patch 'groups/clear_for/:round_id' => 'groups#clear_groups_for_round', :as => :clear_groups_for_round
    patch 'groups/r/:round_id' => 'groups#update_for_round'
    patch 'groups/create_for_round/:round_id' => 'groups#create_groups_for_round', :as => :create_groups_for_round
    patch 'groups/add_everyone_to_all/:round_id' => 'groups#add_everyone_to_all_groups', :as => :fm_mbf_special_fill

    delete 'registration_groups/:id' => 'groups#destroy_registration_group', :as => :delete_from_group

    patch 'groups/autogenerate/:round_id' => 'groups#autogenerate_group', :as => :generate_groups
    get 'groups/generate/:group_id/:direction(/:n)' => 'groups#top_low_to_group', :as => :top_low_groups
    get 'groups/fill/:round_id(/:n)' => 'groups#fill_remaining_groups', :as => :fill_remaining

    post '/confirm' => 'registrations#confirm'
    get '/my_registration' => 'registrations#edit'
    get '/my_schedule' => 'registrations#schedule'

    get '/competition' => 'competitions#show'
    patch '/competition' => 'competitions#update'
    get '/competition/setup' => 'competitions#setup'
    patch '/competition/import/:competition_id' => 'competitions#import_competition', :as => :competition_import
    post '/competition/reset' => 'competitions#reset'
    patch '/competition/import_wcif' => 'competitions#import_wcif', :as => :import_wcif
    patch '/competition/export_wcif' => 'competitions#export_wcif', :as => :export_wcif

    root to: 'visitors#index'

    get '/wca_callback' => 'sessions#create'
    get '/signin' => 'sessions#new', :as => :signin
    post '/signin' => 'sessions#signin_with_wca', :as => :signin_with_wca
    get '/wca_down' => 'sessions#anon_staff'
    post '/wca_down' => 'sessions#login_anon_staff'
    get '/signout' => 'sessions#destroy', :as => :signout
  end
end

app/models/staff_team.rb
class StaffTeam < ApplicationRecord
  has_many :staff_team_members, inverse_of: :staff_team, dependent: :destroy
  has_many :registrations, through: :staff_team_members
  has_many :scramble_events, through: :registrations
  has_many :users, through: :registrations
  has_many :staff_teams_groups, inverse_of: :staff_team, dependent: :delete_all

  accepts_nested_attributes_for :staff_team_members

  validates_presence_of :name

  def leaders
    staff_team_members.select(&:team_leader).map(&:name)
  end

  def to_wcif
    {
      "name": self.name,
      "comments": self.comments,
      "members": staff_team_members.map(&:to_wcif),
    }
  end

  def team_id
    friendly_id = id
    if name =~ /Team/
      friendly_id = name.sub(/.*(Team #(?<n>[0-9]*).*)/, '#\k<n>')
    end
    friendly_id
  end

  def self.as_resources(user_ids_selected, except_team_ids=[])
    resources = []
    StaffTeam.includes(:users).where.not(id: except_team_ids).order(:name).each do |st|
      selected_users_in_team = st.users.select { |u| user_ids_selected.include?(u.id) }
      if selected_users_in_team.any?
        resources << {
          "id": "team_#{st.id}",
          "title": st.name,
          "children": selected_users_in_team.map do |u|
            {
              id: "#{st.id}-#{u.id.to_s}",
              title: u.name,
            }
          end,
        }
      end
    end
    resources
  end
end

app/controllers/staff_teams_controller.rb
class StaffTeamsController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_unless_admin!, except: [:index, :show, :schedule]
  before_action :redirect_unless_staff!
  before_action :set_staff_team, only: [:show, :edit, :update, :destroy]
  before_action :set_staff_available, only: [:edit, :update]

  # GET /staff_teams
  def index
    @staff_teams = StaffTeam.all.order(:id).includes(staff_team_members: { registration: [:user] })
  end

  # GET /staff_teams/1
  def show
    @scramblers_per_event = @staff_team.scramble_events.group(:event_id).count
  end

  # GET /staff_teams/new
  def new
    @staff_team = StaffTeam.new
  end

  # GET /staff_teams/1/edit
  def edit
    @scramblers_per_event = @staff_team.scramble_events.group(:event_id).count
  end

  # POST /staff_teams
  def create
    @staff_team = StaffTeam.new(staff_team_params)

    if @staff_team.save
      flash[:success] = 'Staff team was successfully created.'
      redirect_to edit_staff_team_path(@staff_team)
    else
      render :new
    end
  end

  def schedule
    # NOTE: this was created for Euro 2018: we had several staff teams,
    # and one "booth" team. I needed, when showing the booth team,
    # to display the other teams the members were in to see possible gap in schedule
    @all_events = []
    @staff_team = StaffTeam.includes({
      users: {
        registration: {
          groups: [],
          staff_registrations_groups: {
            group: [:round]
          },
          staff_teams_groups: {
            group: [:round]
          }
        }
      }
    }).find(params[:staff_team_id])
    side_event = ["333mbf", "444bf", "555bf"]
    @staff_team.users.each do |u|
      @all_events << u.registration.staff_registrations_groups.map { |rg| rg.group.to_event(u, true) }
      groups = u.registration.groups
      @all_events << groups.map { |g| g.to_event(u) }
      staff_groups = u.registration.staff_teams_groups.map(&:group)
      staff_groups.reject! do |g|
        side_event.include?(g.event_id) && groups.include?(g)
      end
      @all_events << staff_groups.map { |g| g.to_event(u, true) }
    end
    @all_events.flatten!
    user_ids_selected = @staff_team.users.map(&:id).uniq
    @resources = StaffTeam.as_resources(user_ids_selected, [@staff_team.id])
  end

  # PATCH/PUT /staff_teams/1
  def update
    case params[:registrations_action]
    when "add-selected"
      return add_selected_to_team
    when "remove-selected"
      return remove_selected_from_team
    when "update"
      if @staff_team.update(staff_team_params)
        flash[:success] = 'Staff team was successfully updated.'
        redirect_to edit_staff_team_path(@staff_team)
      else
        render :edit
      end
    else
      raise "Unrecognized action #{params[:registrations_action]}"
    end
  end

  # DELETE /staff_teams/1
  def destroy
    @staff_team.destroy
    flash[:success] = 'Staff team was successfully destroyed.'
    redirect_to staff_teams_url
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_staff_team
    @staff_team = StaffTeam.includes({ staff_team_members: { registration: [:user, :scramble_events, :registration_detail] }}).find(params[:id] || params[:staff_team_id])
  end

  def set_staff_available
    existing_ids = @staff_team.staff_team_members.map { |m| m.registration_id }
    @staff_available = Registration.staff_available.includes(:user).reject { |r| existing_ids.include?(r.id) }
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def staff_team_params
    params.require(:staff_team).permit(:comments, :name, :staff_team_members_attributes => [:id, :team_leader])
  end

  def selected_registrations_ids
    params.require(:selected_registrations).split(',').map { |r| r.split('-')[1].to_i }
  end

  def add_selected_to_team
    registration_ids = selected_registrations_ids
    existing_ids = @staff_team.staff_team_members.map { |m| m.registration_id }
    registration_ids.reject { |id| existing_ids.include?(id) }.each do |id|
      @staff_team.staff_team_members.build(registration: Registration.find(id))
    end
    if @staff_team.save
      flash[:success] = "Successfully added people to team"
    else
      flash[:danger] = "Couldn't save staff team, maybe you try to add the same person twice?"
    end
    redirect_to edit_staff_team_path(@staff_team)
  end

  def remove_selected_from_team
    registration_ids = selected_registrations_ids
    @staff_team.staff_team_members.where(registration_id: registration_ids).map(&:destroy)
    redirect_to edit_staff_team_path(@staff_team)
  end
end

app/helpers/staff_teams_helper.rb
module StaffTeamsHelper
end

app/views/staff_teams/_form.html.erb
<div class="col-xs-12 col-md-6">
  <%= simple_form_for(@staff_team) do |f| %>
    <input id="hidden_selection" name="selected_registrations" type="hidden" value=""/>
    <%= f.error_notification %>

    <div class="form-inputs">
      <%= f.input :name %>
      <%= f.input :comments %>
    </div>
    <%#FIXME: DRY this up%>
    <table data-toggle="table"
           data-click-to-select="true"
           class="table table-hover"
           id="table-staff">
      <thead>
        <tr>
          <th data-checkbox="true" data-field="state"></th>
          <th data-field="name">
            Staff name
          </th>
          <th class="col-xs-2">Scrambles for</th>
          <th class="col-xs-2">Team leader</th>
        </tr>
      </thead>
      <tfoot>
        <tr>
          <td colspan="4">
            <div class="pull-right">
              <button type="submit" class="btn btn-primary" name="registrations_action" value="update">
                <% if f.object.new_record? %>
                  Create staff team
                <% else %>
                  Update staff team
                <% end %>
              </button>
            </div>
            <div class="pull-left" id="delete-button-container" style="display: none;">
              <button type="submit" class="btn btn-danger" name="registrations_action" value="remove-selected">
                <%= icon 'trash', "Remove selected" %>
              </button>
            </div>
        </tr>
      </tfoot>
      <tbody>
        <%= f.simple_fields_for :staff_team_members, f.object.staff_team_members.sort_by(&:name) do |stm|%>
          <tr id="registration-<%= "#{stm.object.registration_id}" %>">
            <td></td>
            <td>
              <%= link_to stm.object.name, edit_registration_path(stm.object.registration_id), target: "_blank" %>
              <%= stm.hidden_field :id %>
              <span class="new-group-number"></span>
            </td>
            <td><%= render "shared/event_id_collection", event_ids: stm.object.registration.scramble_events.map(&:event_id) %></td>
            <td>
              <%= stm.input_field :team_leader, label: false, class: "checkbox-leader" %>
            </td>
          </tr>
        <% end %>
      </tbody>
    </table>
    <hr/>
    <% unless @staff_team.id %>
      <%= alert :info, "You will be able to add people to the team when created.", note: true %>
    <% else %>
      <table data-toggle="table"
             data-click-to-select="true"
             data-search="true"
             class="table table-hover"
             id="table-staff-available">
        <thead>
          <tr>
            <th data-checkbox="true" data-field="state"></th>
            <th data-field="name">
              Staff available (<%= @staff_available.size %>)
            </th>
          </tr>
        </thead>
        <tbody>
          <% @staff_available.each do |sa|%>
            <tr id="registration-<%= "#{sa.id}" %>">
              <td></td>
              <td>
                <%= sa.name %>
                <span class="new-group-number"></span>
              </td>
            </tr>
          <% end %>
        </tbody>
      </table>
      <div id="button-add-to-team" class="pull-left search" style="display: none;">
        <button type="submit" class="btn btn-success" name="registrations_action" value="add-selected">
          <%= icon 'check', "Add selected to the team" %>
        </button>
      </div>
    <% end %>
  <% end %>
</div>

<script>

var showHide = function(e) {
  var staffTable = $("#table-staff");
  $("#delete-button-container").toggle(staffTable.bootstrapTable('getAllSelections').length > 0);
};

$(document).ready(function () {
  $('.checkbox-leader').on('click', function(e) {
    e.stopPropagation();
  });
  // see: http://bootstrap-table.wenzhixin.net.cn/documentation/
  $('#table-staff').on('check.bs.table uncheck.bs.table check-all.bs.table uncheck-all.bs.table', showHide);

  var initCheckboxesValues = function($table) {
    $table.find('tr td input[type="checkbox"]').each(function(index) {
      $(this).val($(this).parents('tr').attr('id'));
    });
  };
  initCheckboxesValues($('#table-staff-available'));
  initCheckboxesValues($('#table-staff'));
  var buttonAdd = $('#button-add-to-team');
  buttonAdd.insertBefore($('#table-staff-available').parent().parent().parent().find('.search'));
  buttonAdd.show();
});

setupSelectTable("#table-staff-available", "#button-add-to-team", "#hidden_selection");
setupSelectTable("#table-staff", "#delete-button-container", "#hidden_selection");

</script>

app/views/staff_teams/edit.html.erb
<h1>Editing team: "<%= @staff_team.name %>"</h1>
<p><%= @staff_team.registrations.size %> people in there.</p>

<p>Number of scramblers per event:</p>
<p>
<% Event.all.each do |e| %>
  <%= render "shared/event", event: e %>: <%= @scramblers_per_event[e.id] || 0 %>,
<% end %>
</p>
<div class="row">
  <%= render 'form', staff_team: @staff_team %>
</div>

<%= link_to 'Show', @staff_team %> |
<%= link_to 'Back', staff_teams_path %>

app/views/staff_teams/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Staff Teams</h1>

<table data-toggle="table" class="table">
  <thead>
    <tr>
      <th>Name</th>
      <th class="col-xs-1">People</th>
      <th class="col-xs-3">Leader</th>
    </tr>
  </thead>

  <tbody>
    <% @staff_teams.each do |staff_team| %>
      <tr>
        <td>
          <%= link_to render("shared/team_name", team: staff_team), staff_team %>
          <% if current_user.can_manage_competition? %>
            <%= link_to icon('pencil'), edit_staff_team_path(staff_team), class: "btn btn-primary btn-sm" %>
            <%= link_to icon('trash'), staff_team, method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-sm" %>
          <% end %>
        </td>
        <td><%= staff_team.registrations.size %></td>
        <td><%= array_to_s(staff_team.leaders) %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<% if current_user.can_manage_competition? %>
  <%= link_to 'New Staff Team', new_staff_team_path %>
<% end %>

app/views/staff_teams/new.html.erb
<h1>New Staff Team</h1>

<%= render 'form', staff_team: @staff_team %>

<%= link_to 'Back', staff_teams_path %>

app/views/staff_teams/schedule.html.erb
<h4>Schedule for <%= @staff_team.name %></h4>

<div class="row">
  <div id="calendar" class="col-xs-12"></div>
</div>
<script>

let options = {
  header: {
    left: 'prev,next',
    center: 'title',
    right: 'timelineDay'
  },
  titleFormat: "dddd, MMMM Do YYYY",
  defaultView: 'timelineDay',
  slotDuration: '00:30:00',
  events: <%= raw(@all_events.to_json) %>,
  resources: <%= raw(@resources.to_json) %>,
  eventRender: function(event, element) {
    if (event.staff_event) {
      element.addClass("staff_event");
    }
  },
};

setupFullCalendarOn("#calendar", '<%= managed_competition.start_date %>', 1, "default", options, false);

</script>

app/views/staff_teams/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <%= link_to 'Back to teams\' index', staff_teams_path %>
</p>

<p>
<strong>Name:</strong>
<%= @staff_team.name %>
</p>

<% unless @staff_team.comments.blank? %>
  <p>
  <strong>Comments:</strong>
  <%= @staff_team.comments %>
  </p>
<% end %>

<p>
<strong>Leader:</strong>
<%= array_to_s(@staff_team.leaders) %>
</p>

<table class="table table-hover"
       id="table-accepted">
  <thead>
    <tr>
      <th>Name</th>
      <th>Events</th>
      <th>Scrambles for</th>
      <th>Runner only</th>
    </tr>
  </thead>
  <tbody>
    <% @staff_team.registrations.sort_by(&:name).each do |registration| %>
      <tr>
        <td>
          <% if current_user.can_manage_competition? %>
            <%= link_to registration.name, edit_registration_path(registration) %>
          <% else %>
            <%= registration.name %>
          <% end %>
        </td>
        <td>
          <%= render "shared/event_id_collection", event_ids: registration.events %>
        </td>
        <td><%= render "shared/event_id_collection", event_ids: registration.scramble_events.map(&:event_id) %></td>
        <td><%= registration.details.runner_only ? "yes" : "" %></td>
      </tr>
    <% end %>
  </tbody>
</table>
<p>Number of scramblers per event:</p>
<p>
<% Event.all_real.each do |e| %>
  <%= render "shared/event", event: e %>: <%= @scramblers_per_event[e.id] || 0 %>
  <br/>
<% end %>
</p>
<% if current_user.can_manage_competition? %>
  <%= link_to 'Edit', edit_staff_team_path(@staff_team) %> |
<% end %>