config/routes.rb
Rails.application.routes.draw do
  scope "(:locale)", locale: /#{I18n.available_locales.join("|")}/ do
    resources :public_guests, except: [:show]
    resources :schedule_events, except: [:show]
    resources :rounds, only: [:index, :edit, :update] do
      patch 'assign_stations' => 'rounds#assign_stations'
    end

    get '/schedule' => 'rounds#schedule'

    get '/wcif' => 'registrations#show_wcif'

    #FIXME: removed in favor of doing this in the WCA website
    #patch 'rounds/add/:event_id' => 'rounds#add', :as => :add_round
    #patch 'rounds/remove/:event_id' => 'rounds#remove', :as => :remove_round

    get 'registrations/random' => 'registrations#random'

    resources :registrations, only: [:index, :edit, :update] do
      get 'groups' => 'groups#show_for_registration'
      get 'schedule' => 'registrations#schedule'
    end

    get 'registrations/staff' => 'registrations#staff'
    get 'registrations/psy/:event_id' => 'registrations#psych_sheet'

    get 'mails' => 'registrations#mails'
    get 'names' => 'registrations#names'
    get 'badges' => 'registrations#badges'
    get 'top3' => 'registrations#top3'
    get 'registrations/cleanup' => 'registrations#cleanup'

    get 'printing' => 'printing#index'
    get 'printable_schedules' => 'printing#printable_schedules'
    get 'printable_groups' => 'printing#printable_groups'
    get 'printable_groups_only' => 'printing#printable_groups_only'
    get 'printable_groups_schedule' => 'printing#printable_groups_schedule'
    get 'printable_rounds_schedule' => 'printing#printable_rounds_schedule'
    get 'printable_teams' => 'printing#printable_teams'
    get 'rooms_side' => 'printing#rooms_side'

    resources :groups, param: :group_id
    resources :groups, only: [] do
      patch 'staff' => 'groups#update_staff'
    end

    resources :staff_teams do
      get 'schedule' => 'staff_teams#schedule'
    end

    get 'groups-schedule' => 'groups#schedule', :as => :groups_schedule
    get 'groups/e/:event_id' => 'groups#show_for_event', :as => :groups_for_event
    get 'groups/r/:round_id' => 'groups#show_for_round', :as => :groups_for_round
    get 'groups/for_round/:round_id' => 'groups#groups_repartition_for_round', :as => :groups_repartition_for_round
    patch 'groups/move_to/:round_id/(:group_id/:registration_ids)' => 'groups#move_registrations_to_group', :as => :move_to_group
    patch 'groups/drop_group_from/:round_id(/:registration_ids)' => 'groups#drop_groups_from_round', :as => :drop_group_for_round
    patch 'groups/clear_for/:round_id' => 'groups#clear_groups_for_round', :as => :clear_groups_for_round
    patch 'groups/r/:round_id' => 'groups#update_for_round'
    patch 'groups/create_for_round/:round_id' => 'groups#create_groups_for_round', :as => :create_groups_for_round
    patch 'groups/add_everyone_to_all/:round_id' => 'groups#add_everyone_to_all_groups', :as => :fm_mbf_special_fill

    delete 'registration_groups/:id' => 'groups#destroy_registration_group', :as => :delete_from_group

    patch 'groups/autogenerate/:round_id' => 'groups#autogenerate_group', :as => :generate_groups
    get 'groups/generate/:group_id/:direction(/:n)' => 'groups#top_low_to_group', :as => :top_low_groups
    get 'groups/fill/:round_id(/:n)' => 'groups#fill_remaining_groups', :as => :fill_remaining

    post '/confirm' => 'registrations#confirm'
    get '/my_registration' => 'registrations#edit'
    get '/my_schedule' => 'registrations#schedule'

    get '/competition' => 'competitions#show'
    patch '/competition' => 'competitions#update'
    get '/competition/setup' => 'competitions#setup'
    patch '/competition/import/:competition_id' => 'competitions#import_competition', :as => :competition_import
    post '/competition/reset' => 'competitions#reset'
    patch '/competition/import_wcif' => 'competitions#import_wcif', :as => :import_wcif
    patch '/competition/export_wcif' => 'competitions#export_wcif', :as => :export_wcif

    root to: 'visitors#index'

    get '/wca_callback' => 'sessions#create'
    get '/signin' => 'sessions#new', :as => :signin
    post '/signin' => 'sessions#signin_with_wca', :as => :signin_with_wca
    get '/wca_down' => 'sessions#anon_staff'
    post '/wca_down' => 'sessions#login_anon_staff'
    get '/signout' => 'sessions#destroy', :as => :signout
  end
end

app/controllers/groups_controller.rb
class GroupsController < ApplicationController
  before_action :authenticate_user!
  before_action :redirect_unless_admin!, except: [:show, :schedule]
  before_action :redirect_unless_staff!, except: [:show]
  before_action :redirect_unless_can_view_groups!
  before_action :set_group, only: [:destroy, :edit, :update, :update_staff, :show]

  SINGLE = %w(333bf 444bf 555bf 333fm 333mbf).freeze
  PREFIXES = %w([Su] [Mo] [Tu] [W] [T] [F] [Sa]).freeze

  DEFAULT_GROUP_SIZE=20

  def top_low_to_group
    max_in_group = params[:n]&.to_i || DEFAULT_GROUP_SIZE
    group = Group.find(params[:group_id])
    top_low = params.require(:direction)
    event = Event.find(group.event_id)
    registrations = Registration.includes(:user, :personal_bests, :registration_groups).with_event_without_group_for(group.round, :user).sort_by do |r|
      r.best_for(event.id, "average")&.as_solve_time || SolveTime::SKIPPED
    end

    group_size = group.registrations.size
    while group_size < max_in_group && !registrations.empty?
      r = top_low == "low" ? registrations.pop : registrations.shift
      group_size += 1
      group.registration_groups.build(registration: r)
    end

    group.save

    redirect_to groups_for_event_path(event.id)
  end

  def fill_remaining_groups
    max_in_group = params[:n]&.to_i || DEFAULT_GROUP_SIZE
    round = Round.find(params[:round_id])
    event = Event.find(round.event_id)
    unless round.r_id == 1
      flash[:warning] = "Can't generate groups for non first round!"
      return redirect_to groups_for_round_path(round.id)
    end
    groups = Group.for_round(round.id).includes(registration_groups: { registration: [:user] }).order(id: :desc)
    registrations = Registration.includes(:user, :personal_bests, :registration_groups).with_event_without_group_for(round, :user).sort_by do |r|
      r.best_for(event.id, "average")&.as_solve_time || SolveTime::SKIPPED
    end

    groups.each do |g|
      slot_available = max_in_group - g.registrations.size
      if slot_available <= 0
        next
      end
      to_add = registrations.slice!(0, slot_available)
      to_add&.each do |r|
        g.registration_groups.build(registration: r)
      end
      g.save
    end
    redirect_to groups_for_event_path(event.id)
  end

  def autogenerate_group
    @round = Round.find(params[:round_id])
    unless @round.r_id == 1
      flash[:warning] = "Can't generate groups for non first round!"
      return redirect_to groups_for_round_path(@round.id)
    end
    Group.clear_for_round(@round.id)
    @event = Event.find(@round.event_id)
    @groups = Group.for_round(@round.id).includes(registration_groups: { registration: [:user] })
    sort_column = SINGLE.include?(@event.id) ? "single" : "average"

    @registrations = Registration.with_event(@event.id, [:user, :personal_bests, :registration_groups]).sort_by do |r|
      r.best_for(@event.id, sort_column)&.as_solve_time || SolveTime::SKIPPED
    end

    if @groups.empty? || @registrations.empty?
      flash[:warning] = "No groups or registrations to distribute the data"
      return redirect_to groups_for_round_path(@round.id)
    end
    @group_ids = @groups.map(&:id)

    # TODO: this is a bit messy, clean it
    # TODO: the actual distribution we want is: last first, then spread the
    # top solvers on groups with id = 1 % 5 (front and featured row)
    chunk_size = (@registrations.size / @groups.size).to_i
    index = 0
    group_id = 0
    @registrations.each do |r|
      @groups[group_id].registration_groups.build(registration: r)
      index += 1
      if index%chunk_size == 0
        index = 0
        group_id += 1
        if group_id == @groups.size
          group_id -= 1
        end
      end
    end

    @groups.each(&:save)

    flash[:success] = "Done"
    redirect_to groups_for_event_path(@event.id)
  end

  def index
    if params[:generate_colors] == "true"
      color_indexes = {}
      Group::COLORS.each do |k,v|
        color_indexes[k] = Group::COLORS.keys.index(k)
      end
      PersonRoundColor.delete_all
      all_entries = []
      Round.includes(groups: { registrations: [:user] }).where(r_id: 1).where.not(event_id: "333fm").each do |r|
        done_one = false
        r.groups.each do |g|
          if r.event_id == "333mbf" && done_one
            break
          end
          done_one = true
          g.registrations.each do |reg|
            all_entries << PersonRoundColor.new(color: color_indexes[g.color], wca_id: reg.user.wca_id, event_id: r.event_id)
          end
        end
      end
      PersonRoundColor.import(all_entries)
    end
  end

  def create
    @repeat_start = params.require(:repeat_start).to_i
    @repeat_end = params.require(:repeat_end).to_i
    all_good = true

    if @repeat_end - @repeat_start <= 0
      @group = Group.new(group_params)
      all_good = @group.save
    else
      (@repeat_start..@repeat_end).each do |i|
        this_group_params = group_params
        this_group_params[:name] += " #{i}"
        @group = Group.new(this_group_params)
        unless @group.save
          all_good = false
          break
        end
      end
    end

    if all_good
      flash[:success] = "Group(s) successfully created!"
      redirect_to groups_for_round_path(@group.round_id)
    else
      render :index
    end
  end

  def create_groups_for_round
    @round = Round.includes(:groups).find(params[:round_id])
    number = params.require(:n).to_i
    duration_in_minutes = params.require(:duration).to_i
    start_number = (@round.groups.map(&:group_number).max || 0) + 1
    group_start_time = @round.start
    group_end_time = group_start_time + duration_in_minutes.minutes
    group_end_time = @round.end if group_end_time > @round.end
    number.times do
      group_name = "#{@round.name} Group #{start_number}"
      @round.groups.create!(name: group_name, start: group_start_time,
                            end: group_end_time, color: "blue",
                            activity_code: "#{@round.activity_code}-g#{start_number}",
                            wcif_id: Competition.next_activity_wcif_id)
      start_number += 1
    end
    flash[:success] = "#{number} group(s) of #{duration_in_minutes} min successfully created!"
    redirect_to groups_for_round_path(@round)
  end


  def destroy
    @group.destroy
    redirect_to groups_for_round_path(@group.round_id)
  end

  def update_staff
    case params[:staff_action]
    when "teams-add-selected"
      return add_selected_staff_teams_to_group
    when "teams-remove-selected"
      return remove_selected_staff_teams_from_group
    when "registrations-remove-selected"
      return remove_selected_staff_people_from_group
    when "registrations-add-selected"
      return add_selected_staff_people_to_group
    when "registrations-update-roles"
      return update_roles_for_individual_staff
    else
      raise "Unrecognized action #{params[:registrations_action]}"
    end
  end

  def edit
    set_staff_teams!
  end

  def show
  end

  def update
    respond_to do |format|
      if @group.update(group_params)
        format.html { redirect_to edit_group_path(@group), flash: { success: 'Group was successfully updated.' }}
        format.json { render json: @group, status: :ok }
      else
        format.html do
          set_staff_teams!
          flash[:danger] = 'Error when updating group'
          render :edit
        end
        format.json { render json: @group.errors, status: :unprocessable_entity }
      end
    end
  end

  def show_for_event
    @event = Event.find(params[:event_id])
    @round = Round.where(event_id: @event.id).order(r_id: :asc).first
    respond_to do |format|
      format.html { set_groups_ungrouped! if @round }
      format.json { set_groups! if @round }
    end
    @groups ||= []
    render :show_for_round
  end

  def show_for_round
    @round = Round.find(params[:round_id])
    @event = Event.find(@round.event_id)
    respond_to do |format|
      format.html { set_groups_ungrouped! }
      format.json { set_groups! }
    end
  end

  def groups_repartition_for_round
    @round = Round.find(params[:round_id])
    @event = Event.find(@round.event_id)
    set_groups_ungrouped!(ignore_special: true)
  end

  def move_registrations_to_group
    # patch 'groups/move_to/:round_id/(:group_id/:registration_ids)' => 'groups#move_registrations_to_group', :as => :move_to_group
    @round = Round.includes(:groups).find(params[:round_id])
    groups_for_round = @round.groups.map(&:id)
    # NOTE: to_i is defined for nil
    group_id = (groups_for_round & [params[:group_id].to_i]).first
    @group = Group.find(group_id)
    registration_ids = params[:registration_ids]&.split(",") || []
    # Destroy existing groups for these registrations
    RegistrationGroup.where(group_id: groups_for_round, registration_id: registration_ids).destroy_all
    # Rebuild with the correct group, for actually existing ids
    Registration.where(id: registration_ids).each do |r|
      if r.events.include?(@round.event_id)
        new_rg = RegistrationGroup.new(group_id: @group.id, registration_id: r.id)
        # validation is expensive, we already did some kind of manual check
        new_rg.save!(validate: false)
      end
    end
    render json: {}, status: :ok
  end

  def add_everyone_to_all_groups
    # Special action for FM and 333MBF as they are attempt-based!
    @round = Round.includes(:groups).find(params[:round_id])
    unless ["333mbf", "333fm"].include?(@round.event_id)
      flash[:danger] = "This action is only valid for MBF and FM."
      return redirect_to groups_for_round_path(@round)
    end
    groups_for_round = @round.groups.map(&:id)
    RegistrationGroup.where(group_id: groups_for_round).destroy_all
    new_registration_groups = []
    competitors_registered = Registration.with_event(@round.event_id)
    @round.groups.each do |g|

app/helpers/groups_helper.rb
module GroupsHelper
end

app/views/groups/_form_table_for_group.html.erb
<%= simple_form_for group,
                    url: groups_for_round_path(@round.id),
                    html: { id: "form-for-#{group_id}" },
                    method: :patch do |eg| %>
  <%= render "action_input_group", available_groups: @groups %>
  <table data-toggle="table"
         data-click-to-select="true"
         data-search="true"
         class="table table-hover panel-body">
    <thead>
      <tr>
        <th data-checkbox="true" data-field="state"></th>
        <th class="search-cell" data-field="name">
        </th>
      </tr>
    </thead>
    <tbody>
      <%= eg.simple_fields_for :registration_groups, group.registration_groups do |f|%>
        <% registration_teams = f.object.staff_teams.map(&:team_id) %>
        <tr class="<%= "danger" unless (group_teams & registration_teams).empty? %>">
          <td></td>
          <% line_id = "#{f.object.group_id}_#{f.object.registration_id}" %>
          <td id="<%= line_id %>">
            <%= f.object.name %>
            <% unless (f.object.registration.events & ["333mbf"]).empty? %>
              M
            <% end %>
            <% unless (f.object.registration.events & ["444bf", "555bf"]).empty? %>
              BBF
            <% end %>
            <%= array_to_s(registration_teams) %>

            <%= link_to icon('trash'), delete_from_group_path(f.object.id), method: :delete, data: { confirm: 'Are you sure?' }, class: "btn btn-danger btn-xs pull-right" if f.object.id %>
            <%= f.hidden_field :id %>
            <%= f.hidden_field :registration_id %>
            <%= f.hidden_field :group_id, class: "hidden-group-input" %>
            <span class="new-group-number"></span>
          </td>
        </tr>
      <% end %>
    </tbody>
  </table>
<% end %>

app/views/groups/_group_panel.html.erb
<% group_id ||= "nogroup" %>
<% title ||= "untitled" %>
<% color ||= "white" %>
<% staff_teams_ids = group.id.nil? ? [] : group.staff_teams.map(&:team_id) %>
<div class="col-xs-6 col-sm-3">
  <div class="panel <%= "panel-#{color}" unless color.blank? %>">
    <div class="panel-heading heading-as-link collapsed" data-toggle="collapse" data-target="#collapse-<%= group_id %>">
      <h3 class="panel-title">
        <% if staff_teams_ids.any? %>
          [<%= array_to_s(staff_teams_ids) %>]
        <% end %>
        <%= title %>
        <span class="badge"><%= group.registration_groups.size %></span>
        <%= link_to icon('pencil'), edit_group_path(group.id) if group.id %>
        <%= link_to icon('trash'), group_path(group.id), id: "delete-group-#{group.id}", method: "delete" if group.id %>
        <%= link_to "+top", top_low_groups_path(group.id, "top") if group.id %>
        <%= link_to "+low", top_low_groups_path(group.id, "low") if group.id %>
        <span class="collapse-indicator"></span>
      </h3>
    </div>
    <div id="collapse-<%= group_id %>" class="panel-collapse collapse panel-groups">
    <%= render "form_table_for_group", group: group, group_id: group_id, group_teams: staff_teams_ids %>
    </div>
  </div>
</div>
<script>
// Move stuff around
$(document).ready(function () {
  setupForm($("#form-for-<%= group_id %>"), "<%= group_id %>");

  $('#delete-group-<%= group.id %>').on("click", function(e) {
    if(!confirm("Delete the group?")) {
      e.preventDefault();
      e.stopPropagation();
    }
  });
});

</script>

app/views/groups/_nav.html.erb
<% active_event ||= "" %>
<div class="container-fluid">
  <div class="row">
    <div id="groups-nav">
      <ul class="nav nav-tabs">
        <li role="presentation" class="<%= "active" if active_event.blank? %>">
          <%= link_to(icon('plus'), groups_path) %>
        </li>
        <% Event.all.each do |e| %>
          <li role="presentation" class="<%= "active" if e.id == active_event %>">
            <%= link_to(render('shared/event', event: e, placement: "bottom"), groups_for_event_path(e.id)) %>
          </li>
        <% end %>
      </ul>
    </div>
    <% unless active_event.blank? %>
      <div id="rounds-nav">
        <ul class="nav nav-pills">
          <% rounds = Round.where(event_id: active_event).order(r_id: :asc) %>
          <% rounds.each do |r| %>
            <li role="presentation" class="<%= "active" if @round.id == r.id %>">
              <%= link_to(r.name, groups_for_round_path(r.id)) %>
            </li>
          <% end %>
        </ul>
      </div>
    <% end %>
    <div id="groups-content">
      <%= yield %>
    </div>
  </div>
</div>

app/views/groups/groups_repartition_for_round.html.erb
<%= render 'nav', active_event: @event.id do %>
  <h1>Editing groups for <%= @round.name %></h1>
  <p>
  <a href="#" onclick="$('.collapse').collapse('show');">Expand all</a>
  | <a href="#" onclick="$('.collapse').collapse('hide');">Collapse all</a>
  </p>
  <p>
  Sort by : <%= link_to "Name", "#", id: "sort_name_link", class: "icon-after alpha_asc" %>, <%= link_to "Psychsheet", "#", id: "sort_pb_link", class: "icon-after num_desc" %>
  </p>
  <p>
  Each group has two actions to add groups of competitors to them:
  </p>
  <ul>
    <li><%= icon("toggle-up") %>: add the top N people to the group</li>
    <li><%= icon("toggle-down") %>: add the bottom N people to the group</li>
  </ul>
  <p class="form-inline">
  Where N is <%= number_field_tag("N", 20, min: 1, class: "form-control inline-integer", id: "batch-size") %>.
  </p>
  <p class="form-inline">
  Complementarily, you can <%= link_to("automatically fill", "#", onclick: "autoFill()") %> the groups up to
  <%= number_field_tag("N", 20, min: 1, class: "form-control inline-integer", id: "group-size") %>
  competitors.
  <br/>
  The groups will be filled from last to first, taking the top of the unassigned competitors list, as it is currently sorted.
  </p>

  <% if ["333mbf", "333fm"].include?(@round.event_id) %>
    <%= alert(:warning) do %>
      It looks like you are editing groups for FM or MBF, due to the attempt-based
      nature of the event this group editor won't quite work (because unlike
      other events, all competitors will need to be in all "groups").
      <br/>
      You can click <%= link_to "here", fm_mbf_special_fill_path(@round), method: "patch" %> to fill all the groups automatically.
    <% end %>
  <% else %>
    <p><%= link_to "(Re)Assign stations for this round", round_assign_stations_path(@round), method: :patch %></p>
  <% end %>
  <% if @round.r_id != 1 %>
    <%= alert(:info, "If no competitors show up here, please make sure results are entered in WCA Live, open the next round, sync with the WCA, then import the competition here.", note: false) %>
  <% end %>
  <p>
    <%= link_to "Clear all competitors assignment", clear_groups_for_round_path(@round), method: "patch", class: "btn btn-danger", data: { confirm: "Are you sure?" } %>
  </p>
  <div class="row">
    <div class="col-xs-6 col-md-3">
      <div id="group-0" class="panel panel-default panel-dg">
        <div class="panel-heading">
          <h3 class="panel-title">
            Competitors without groups
            <span class="badge"><%= @all_without_group.size %></span>
          </h3>
        </div>
        <div class="panel-groups list-group">
          <div class="search">
            <input class="form-control" type="text" placeholder="Filter people">
            <span class="glyphicon glyphicon-remove-circle"></span>
          </div>
          <div id="without-group" class="list-people" data-group="0">
            <%= render "registrations_as_list", registrations: @all_without_group, event_id: @round.event_id %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-xs-6 col-md-9">
      <div class="row row-all-existing-groups">
        <% @groups.sort.each do |g| %>
          <%= render 'existing_group_panel', group: g %>
          <div class="may-clearfix"></div>
        <% end %>
      </div>
    </div>
  </div>
  <script>
var drake = dragula($(".list-people").toArray(), {
  removeOnSpill: true,
});

let removeGroupForRegistration = function(registration, revertFunc) {
  return ajaxAction(`<%= drop_group_for_round_path(@round.id) %>/${registration}`,
                    revertFunc);
};

let moveTo = function(to, registration_ids, revertFunc) {
  return ajaxAction(`<%= move_to_group_path(@round.id) %>/${to}/${registration_ids.join(",")}`,
                    revertFunc);
};

drake.on('remove', function(el, container, source) {
  // override removeonspill by adding it back to the 'without-group' div
  let $el = $(el);
  $el.removeClass("gu-hide");
  let $prev = $(container);
  let cancelled = false;
  if ($prev.data("group") != "0") {
    let revert = function() {
      $prev.append($el);
    };
    cancelled = !removeGroupForRegistration($el.data("registration"), revert);
  }
  if (!cancelled) {
    $("#without-group").append($el);
    recomputeSizeForGroups([$prev, $("#without-group")]);
  }
}).on('drop', function(el, target, source, sibling) {
  let $el = $(el);
  let $target = $(target);
  let $source = $(source);
  let to = $target.data("group");
  let from = $source.data("group");
  let registration_id = $el.data("registration");
  let revert = function() {
    $source.append($el);
  };
  if (to == from) {
    return;
  } else if (to == "0") {
    removeGroupForRegistration(registration_id, revert);
  } else {
    moveTo(to, [registration_id], revert);
  }
  recomputeSizeForGroups([$target, $source]);
})

sortGroupsBy = function(attr, asc = true) {
  $(".list-people").each(function (index, element) {
    sortCollectionBy($(this).children(), attr, asc).detach().appendTo($(this));
  });
}

$("#sort_name_link").click(function(ev) {
  ev.preventDefault();
  let asc = $(this).hasClass("alpha_desc");

  $(this).toggleClass("alpha_asc", asc);
  $(this).toggleClass("alpha_desc", !asc);

  sortGroupsBy("name", asc);
});

$("#sort_pb_link").click(function(ev) {
  ev.preventDefault();
  let asc = $(this).hasClass("num_desc");

  $(this).toggleClass("num_asc", asc);
  $(this).toggleClass("num_desc", !asc);

  sortGroupsBy("pb", asc);
});

let selectAndMove = function(ev, side, $group) {
  let groupId = $group.data("group");
  ev.preventDefault();
  ev.stopPropagation();
  let $elems = selectNComps(side);
  let ids = $elems.map((_, el) => $(el).data("registration")).get();
  if (ids.length == 0)
    return;
  if (moveTo(groupId, ids, function() {})) {
    $elems.detach().appendTo($group);
    recomputeSizeForGroups([$group, $("#without-group")]);
  }
}

let autoFill = function() {
  let groupSize = $("#group-size").val();
  let availableCompetitors = $("#group-0");
  let allGroups = $($(".list-people").get().reverse());
  allGroups.each(function(index, group) {
    let $group = $(group);
    let groupId = $group.data("group");
    if (groupId == "0")
      return;
    let competitorsInGroup = $group.find(".list-group-item").length;
    let missing = groupSize - competitorsInGroup;
    if (missing <= 0)
      return;
    let $selected = selectNComps("top", missing);
    if ($selected.length <= 0)
      return;
    let ids = $selected.map((_, el) => $(el).data("registration")).get();
    if (moveTo(groupId, ids, function() {})) {
      $selected.detach().appendTo($group);
    }
  });
  recomputeSizeForGroups(allGroups.map((_, el) => $(el)));
}

// Activate onclick for add top/bottom competitors
$(".panel-dg").each(function(index, el) {
  let $pan = $(el);
  let $group = $pan.find(".list-people");
  $pan.find(".add-top").click(function(ev) {
    selectAndMove(ev, "top", $group);
  });
  $pan.find(".add-bottom").click(function(ev) {
    selectAndMove(ev, "bottom", $group);
  });
});

$(".panel-groups").each((index, el) => {
  let $pan = $(el);
  // The clear search icon
  $pan.find(".search > .glyphicon-remove-circle").click(clearSearch);
  // The clear search icon
  $pan.find(".search > input").change(filterRegistrations);
});

  </script>
<% end %>

app/views/groups/schedule.html.erb
<h4><%= managed_competition.name %> groups schedule</h4>
<%= link_to("Show team id(s) for groups", groups_schedule_path(with_id: true))%>

<div class="row">
  <div id="calendar" class="col-xs-12"></div>
</div>
<script>

let options = {
  events: '<%= groups_schedule_path(format: :json, with_id: params[:with_id]) %>',
  eventClick: function(event, jsEvent, view) {
    $.getScript(event.show_url, function() {});
  },
};

setupFullCalendarOn("#calendar", '<%= managed_competition.start_date %>', '<%= managed_competition.number_of_days %>', "fullcomp", options, false);

</script>

app/views/groups/show_for_round.erb
<%= render 'nav', active_event: @event.id do %>
  <% if @round %>
    <br/>
    <p>This round will occur in room "<%= @round.venue_room.name %>"</p>
    <br/>
    <%= simple_form_for :create_groups,
      url: create_groups_for_round_path(@round.id),
      method: :patch do |f| %>
      <p class="form-inline">
      Want to create <%= number_field_tag("n", 2, min: 1, class: "form-control inline-integer", id: "number-groups") %> groups each lasting <%= number_field_tag("duration", 15, min: 5, class: "form-control inline-integer", id: "duration") %> minutes ?
      <%= f.submit "Do it!", class: "btn btn-primary" %>
      </p>
    <% end %>
    <p><%= link_to "Edit #{@round.name}'s start and end time", edit_round_path(@round) %></p>
    <p><%= link_to "Manage the composition of groups for #{@round.name}", groups_repartition_for_round_path(@round) %></p>
    <div class="row">
      <div id="calendar" class="col-xs-12"></div>
    </div>
    <script>
let additionalOptions = {
  minTime:'<%= (@round.start - 1.hours).strftime("%H:%M:%S") %>',
  maxTime:'<%= (@round.end + 1.hours).strftime("%H:%M:%S") %>',
  events: '<%= groups_for_round_path(@round, format: :json) %>',
  slotDuration: '00:05:00',
  eventRender: function(event, element) {
    if (event.hasOwnProperty('edit_url')) {
      // FIXME: maybe for this it actually makes sense to edit everything in the modal!
      // Should be easier to quickly reassign staff teams/users...
      var newElem = $('<a href="'+event.edit_url+'">Edit group</a>');
      element.find('.fc-content').append("<br/>");
      element.find('.fc-content').append(newElem);
    }
  },
};

setupFullCalendarOn("#calendar", '<%= @round.start.strftime("%Y-%m-%d") %>', 1, "default", additionalOptions, true);

$('#groups-action-collapse').click(function (e) {
  e.preventDefault();
  $('.panel-heading').not('.collapsed').click();
});
$('#groups-action-expand').click(function (e) {
  e.preventDefault();
  $('.panel-heading.collapsed').click();
});
    </script>
  <% end %>
<% end %>